RAW_DATA_FILE_PATH = "./data/raw"
COLS = [
    "Date",
    "Time",
    "Physical Memory Load [%]",
    "Max CPU/Thread Usage [%]",
    "Total CPU Usage [%]",
    "Total CPU Utility [%]",
    "GPU Utilization [%]",
    "GPU D3D Usage [%]",
    "CPU Package Power [W]",
    "GPU Core Power [W]",
    "CPU TDC Limit [%]",
    "Framerate Presented (avg) [FPS]",
    "Framerate Presented (1% low) [FPS]",
    "Framerate Presented (0.1% low) [FPS]",
    "Frame Time Presented (avg) [ms]",
    "CPU Busy (avg) [ms]",
    "GPU Busy (avg) [ms]",
    "CPU Wait (avg) [ms]",
    "GPU Wait (avg) [ms]",
    "CPU (Tctl/Tdie) [°C]",
    "GPU Thermal Diode [°C]",
    "Average Effective Clock [MHz]",
]
